### ISSUE TITLE
switch to pull request reviewers who has approved as method of unblocking PR

### ISSUE THREAD

**Issue by erwinmombay** [google/github-owners-bot#10]
Currently we work off of the "APPROVED" label but once github exposes the usernames of the approvers of a PR we can switch to that to change the status

I pinged github about this a few months ago and they said it was coming up but :man_shrugging: its been a while

**Comment by cramforce** [comment]
Is it a label or a comment?

**Comment by erwinmombay** [comment]
@cramforce currently as label, didn't want to have to parse and normalize comments =X

**Comment by cramforce** [comment]
How do 2 people approve then? Like in our case for an ads and build change.
I don't want to have to 2 that as root approver.

**Comment by erwinmombay** [comment]
@cramforce good point. I'll have to switch to comments for now then.

**Comment by cramforce** [comment]
Lets make the magic word "LGTM"

**Comment by erwinmombay** [comment]
obsolete.
