### ISSUE TITLE
Needs to be less aggressive about picking reviewers

### ISSUE THREAD

**Issue by cramforce** [google/github-owners-bot#17]
<img width="678" alt="screen shot 2017-03-14 at 7 39 21 am" src="https://cloud.githubusercontent.com/assets/89679/23905817/734f7444-0889-11e7-9283-f65a1ebbe2ea.png">

We shouldn't always @-mention the whole team :)

We should probably:

- randomly select one reviewer
- and maybe keep the rest of the list, but remove the @ from the non-selected reviewers

**Comment by cramforce** [comment]
Or maybe it should just never @-mention anyone? Leave it to the PR author to manually assign a reviewer.

**Comment by erwinmombay** [comment]
@cramforce got it

**Comment by erwinmombay** [comment]
i prefer that latter
