### ISSUE TITLE
Don't comment if author has OWNERS

### ISSUE THREAD

**Issue by cramforce** [google/github-owners-bot#25]
See e.g. https://github.com/ampproject/amphtml/pull/8175

I do not need any extra approvals. In that case the bot should not comment.

**Comment by cramforce** [comment]
Ah, maybe there is a different bug: The bot says I'm missing full approvals.

**Comment by erwinmombay** [comment]
yeah, this is a bug. the problem is that it stops at that levels owners. it should really see that you are a root level owner. even though you arent on the list of reviewers that it posts. this is 2nd top priority bug/feature after file level owner.

**Comment by erwinmombay** [comment]
need to add `isInAcestorOwners` check when evaluating `areAllApprovalsMet`

**Comment by erwinmombay** [comment]
comment system is obsolete since github now has approvals api
