### ISSUE TITLE
Provide a comment with instructions at the top of every `OWNERS.yaml` file

### ISSUE THREAD

**Issue by rsimha** [google/github-owners-bot#60]
When someone new to the codebase wants to edit an `OWNERS.yaml` file, it's hard to find the format for declaring owners for individual files / directories, and for declaring a working group as an owner.

A single line comment that points to the `OWNERS.yaml` spec would be useful.

I'm happy to write up a PR if a link exists.

/cc @mrjoro

**Comment by erwinmombay** [comment]
migrated to https://github.com/ampproject/amp-github-apps/issues/282
