### ISSUE TITLE
Automatically assign incoming renovate PRs to the current build cop

### ISSUE THREAD

**Issue by rsimha** [google/github-owners-bot#61]
Incoming [renovate PRs](https://github.com/ampproject/amphtml/pulls/renovate-bot) tend to get ignored by most build cops. The owners bot is in a good position to assign each incoming PR to the current build cop for prompt attention.

We can do two things when a renovate PR is initially created, or a new commit is pushed:

- Assign (or reassign) the PR to the current build cop
- Add the current build cop as reviewer

/cc @danielrozenberg who is working on an API to return the github ID of the current build cop
/cc @mrjoro

**Comment by choumx** [comment]
If externalizing the build cop rotation is difficult, we can decouple it and just rotate it around the set union of OWNERS. Keeping packages up to date is not really related to Travis greenness anyways.

**Comment by rsimha** [comment]
This issue has come up a few times in the recent past.

@erwinmombay could you look into this as you're making owners a blocking check? I believe @danielrozenberg has an in-progress effort for grabbing the github ID of the current build cop, but was running into authentication issues that I'd imagine we can work around.

**Comment by erwinmombay** [comment]
migrated to https://github.com/ampproject/amp-github-apps/issues/284
