### ISSUE TITLE
Is it possible to declare different owners for different lines in a file?

### ISSUE THREAD

**Issue by rsimha** [google/github-owners-bot#62]
For example, `package.json` receives frequent updates from renovate-bot. Often times, the build cop needs to ask others for a review based on the actual dependency being upgraded (the line being changed).

I wonder if the owners bot can eventually figure this out and intelligently assign a reviewer based on which dependency (line) is upgraded (changed).

**Comment by rsimha** [comment]
Related to #59

**Comment by erwinmombay** [comment]
migrated to https://github.com/ampproject/amp-github-apps/issues/283
