### ISSUE TITLE
Include link to matched owners file(s) in GH comments

### ISSUE THREAD

**Issue by cramforce** [google/github-owners-bot#8]
That way people can quickly find alternative approvers.

**Comment by erwinmombay** [comment]
should we include the whole ancestor owner tree? or just at some depth (2?) ?

**Comment by cramforce** [comment]
I thought basically the file(s) that triggered the people that are in the set. Does that make sense?

**Comment by erwinmombay** [comment]
closed through https://github.com/google/github-owners-bot/commit/838910094998005601f8c4c2a173b44daa0b7428
