### ISSUE TITLE
improve owners approval list algorithm

### ISSUE THREAD

**Issue by erwinmombay** [google/github-owners-bot#9]
assuming only 1 file changed in a 3 level deep directory:

original algorithm was very simple:
look for the closest OWNER file for a file changed. The problem with this was that if you were a root owner and the file changed was in a directory 3 levels deep you would be given the owners list of that directory and not be approved right away.

current algorithm:
look for ALL the OWNER files starting from the current directory of the file and its ancestor up to the root accumulating all usernames as possible approvers. This solves the problem of the original algorithm but also is very verbose in its owner listing (even with removing dupes etc).

possible future algorithm:
look for the closest OWNER for a file changed and choose that as a candidate (possibly to post as a comment) but ALSO traverse the ancestor hierarchy in case the current PR author is an ancestor owner and approve the PR right away.

/to @cramforce for comments and suggestions

**Comment by cramforce** [comment]
I think we should always include the "closest" OWNERS, even if they aren't the best candidates in terms of total coverage.

Sorry, my brain is too fried today to completely visualize all the algorithms :)

**Comment by erwinmombay** [comment]
my only question is, should we also list down ancestor owners in the bot comment or just exclude it? (for example, you will always be pinged since you are a root directory owner which seems like a bad thing)

**Comment by cramforce** [comment]
Right, ping the smallest set possible. Being pinged by every issue would kill me.

**Comment by erwinmombay** [comment]
@cramforce lol yes. ill make the update
